### PR TITLE
Feature: velocity button

### PR DESCRIPTION
**Pull request by jamesjwarren**
This directive would be useful for making button animations. There are two states each of which can have a keyframe animation set:
- active
- inactive

The trigger events (e.g. click/mouseeneter/mouseleave) for either state can be set by:
- eventOn
- eventOff

This is an initial PR opened for early review, **NOT ready for merge**.

### CODE REVIEW

**Comment by edoparearyee** [comment]
@jamesjwarren looks good, the only thing i would say is to explain the purpose of the directive and why it exists e.g. give an example of when to use this, like using `$resource` over `$http`

**Comment by edoparearyee** [comment]
simple, well done! :+1:

**Comment by edoparearyee** [comment]
@jamesjwarren is this ready to merge?

**Comment by jamesjwarren** [comment]
Yeh, I'll create the examples page separately.

**Pull request merged**
